### ISSUE TITLE
Fix not working with PhpStorm-172.4155.41

### ISSUE THREAD

**Issue by evgeniy-webmaster** [zheludkovm/LinuxJavaFixes#16]
$ ./opt/PhpStorm-172.4155.41/bin/phpstorm.sh 
java.lang.NoClassDefFoundError: javassist/ClassPool
	at net.x11.patch.XKeysymTransformer.doClass(XKeysymTransformer.java:37)
	at net.x11.patch.XKeysymTransformer.transform(XKeysymTransformer.java:28)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.awt.X11.XWindow.keysymToUnicode(XWindow.java:1034)
	at sun.awt.X11.XWindow.handleKeyPress(XWindow.java:1091)
	at sun.awt.X11.XWindow.handleKeyPress(XWindow.java:1068)
	at sun.awt.X11.XComponentPeer.handleKeyPress(XComponentPeer.java:75)
	at sun.awt.X11.XFocusProxyWindow.handleKeyPress(XFocusProxyWindow.java:81)
	at sun.awt.X11.XBaseWindow.dispatchEvent(XBaseWindow.java:1121)
	at sun.awt.X11.XFocusProxyWindow.dispatchEvent(XFocusProxyWindow.java:73)
	at sun.awt.X11.XBaseWindow.dispatchToWindow(XBaseWindow.java:1086)
	at sun.awt.X11.XToolkit.dispatchEvent(XToolkit.java:504)
	at sun.awt.X11.XToolkit.run(XToolkit.java:618)
	at sun.awt.X11.XToolkit.run(XToolkit.java:534)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: javassist.ClassPool
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more

**Comment by zheludkovm** [comment]
Check your config :
Must be two jars in one directory :
LinuxJavaFixes-1.0.0-SNAPSHOT.jar
javassist-3.12.1.GA.jar

add 
-javaagent:[full path to directory with TWO jar files]/LinuxJavaFixes-1.0.0-SNAPSHOT.jar
to idea64.vmoptions or idea.vmoptions

**Comment by zheludkovm** [comment]
Just tried latest PHP Storm (2017.2.4 evaluate version) - everything is working  
JVM - jdk1.8.0_131
