### ISSUE TITLE
Don't work with PhpStorm 2016.1 on Ubuntu 16.04

### ISSUE THREAD

**Issue by mihdan** [zheludkovm/LinuxJavaFixes#11]
(

**Comment by zheludkovm** [comment]
I will wait 16.04 release and then try.

**Comment by mihdan** [comment]
ok

**Comment by ermolaev** [comment]
i have same issue
```
➜  ~ sh /opt/rubymine/bin/rubymine.sh               
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=250m; support was removed in 8.0
[   2791]   WARN - om.intellij.util.ProfilingUtil - Profiling agent is not enabled. Add -agentlib:yjpagent to idea.vmoptions if necessary to profile IDEA. 
[   4588]   WARN - api.vfs.impl.local.FileWatcher - The current <b>inotify</b>(7) watch limit is too low. <a href="https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit">More details.</a> 
java.lang.NoClassDefFoundError: javassist/ClassPool
	at net.x11.patch.XKeysymTransformer.doClass(XKeysymTransformer.java:37)
	at net.x11.patch.XKeysymTransformer.transform(XKeysymTransformer.java:28)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.awt.X11.XWindow.keysymToUnicode(XWindow.java:1030)
	at sun.awt.X11.XWindow.handleKeyPress(XWindow.java:1087)
	at sun.awt.X11.XWindow.handleKeyPress(XWindow.java:1064)
	at sun.awt.X11.XComponentPeer.handleKeyPress(XComponentPeer.java:75)
	at sun.awt.X11.XFocusProxyWindow.handleKeyPress(XFocusProxyWindow.java:81)
	at sun.awt.X11.XBaseWindow.dispatchEvent(XBaseWindow.java:1125)
	at sun.awt.X11.XFocusProxyWindow.dispatchEvent(XFocusProxyWindow.java:73)
	at sun.awt.X11.XBaseWindow.dispatchToWindow(XBaseWindow.java:1090)
	at sun.awt.X11.XToolkit.dispatchEvent(XToolkit.java:502)
	at sun.awt.X11.XToolkit.run(XToolkit.java:616)
	at sun.awt.X11.XToolkit.run(XToolkit.java:532)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: javassist.ClassPool
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more
```

**Comment by zheludkovm** [comment]
mihdan 
I tried 16.04 and can't reproduce you bug.
tried jdk1.7.0_80 and jdk1.8.0_91, intellij idea and php storm trial edition.
what version of jdk do you use ? Please attach logs from command line.

ermolaev
It looks you don't download javassist-3.12.1.GA.jar
you need to place 
javassist-3.12.1.GA.jar and LinuxJavaFixes-1.0.0-SNAPSHOT.jar into one directory

**Comment by ermolaev** [comment]
after download javassist it work fine.
sorry for the careless reading documentation (

**Comment by mihdan** [comment]
1. Remove LinuxJavaFixes
2. Clone LinuxJavaFixes
3 OK

**Comment by zheludkovm** [comment]
ok, close bug
